"""empty message

Revision ID: 87fda89c48e3
Revises: 26ed300efb6c
Create Date: 2020-10-15 12:05:53.245947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87fda89c48e3'
down_revision = '26ed300efb6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('check', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'check')
    # ### end Alembic commands ###
